import OpenAI from 'openai';

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

// Generate embeddings for document chunks
export const generateEmbedding = async (text: string): Promise<number[]> => {
  const response = await openai.embeddings.create({
    model: 'text-embedding-3-small',
    input: text,
  });
  
  return response.data[0].embedding;
};

// Generate financial insights
export const generateInsights = async (
  documents: string[],
  structuredData: Record<string, any>[]
) => {
  const context = documents.join('\n\n');
  
  const summaryPrompt = `Based on the following financial documents, generate a comprehensive financial summary for this client. Include sections on Income & Tax, Investments & Retirement, Insurance Coverage, Estate Planning, and Key Observations.

Documents:
${context}

Generate a professional, factual summary (500-1000 words) suitable for an advisor to review.`;

  const opportunitiesPrompt = `Based on the following financial documents, identify specific planning opportunities and recommendations. Focus on actionable items like tax optimization, coverage gaps, beneficiary issues, and retirement planning opportunities.

Documents:
${context}

Provide 5-15 specific recommendations in bullet format with priority levels (High/Medium/Low).`;

  const proposalPrompt = `Based on the following financial documents, create a client-facing proposal with sections: Executive Summary, Current Situation, Recommendations, and Next Steps.

Documents:
${context}

Write in a warm, professional tone appropriate for the client (1-2 pages).`;

  const [summaryResponse, opportunitiesResponse, proposalResponse] = await Promise.all([
    openai.chat.completions.create({
      model: 'gpt-4',
      messages: [{ role: 'user', content: summaryPrompt }],
      temperature: 0.7,
    }),
    openai.chat.completions.create({
      model: 'gpt-4',
      messages: [{ role: 'user', content: opportunitiesPrompt }],
      temperature: 0.7,
    }),
    openai.chat.completions.create({
      model: 'gpt-4',
      messages: [{ role: 'user', content: proposalPrompt }],
      temperature: 0.7,
    }),
  ]);

  const disclaimer = "\n\n*This analysis is generated by AI based on uploaded documents. It is intended for informational purposes only and does not constitute financial, tax, or legal advice. Please consult with a qualified professional before making financial decisions.*";

  return {
    summary: summaryResponse.choices[0].message.content + disclaimer,
    opportunities: opportunitiesResponse.choices[0].message.content + disclaimer,
    proposal: proposalResponse.choices[0].message.content + disclaimer,
  };
};

// Generate chat responses
export const generateChatResponse = async (
  message: string,
  context: string[] = [],
  mode: 'personal' | 'general' = 'personal'
) => {
  const systemPrompt = mode === 'personal' 
    ? "You are a financial AI assistant helping a client understand their personal financial situation based on their uploaded documents. Always cite sources when referencing specific information."
    : "You are a financial AI assistant providing general financial education and guidance. Do not reference any personal documents or specific client information.";

  const userPrompt = mode === 'personal' && context.length > 0
    ? `Context from client documents:\n${context.join('\n\n')}\n\nQuestion: ${message}`
    : message;

  const response = await openai.chat.completions.create({
    model: 'gpt-4',
    messages: [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: userPrompt }
    ],
    temperature: 0.7,
  });

  return response.choices[0].message.content;
};
